### ISSUE TITLE
Problem with SFTP uploader (1.2.0)

### ISSUE THREAD

**Issue by evan3334** [olav-st/screencloud#166]
I tried to use the SFTP uploader when taking a screenshot to upload my pictures to my server, but an error message popped up containing this information:
`Upload failed!
Failed to call SFTPUploader.upload()
Traceback (most recent call last):
  File "<string>", line 100, in upload
  File "/home/evan/.local/share/data/screencloud/ScreenCloud/plugins/sftp/modules/paramiko/transport.py", line 1007, in connect
    self.start_client()
  File "/home/evan/.local/share/data/screencloud/ScreenCloud/plugins/sftp/modules/paramiko/transport.py", line 466, in start_client
    raise e
paramiko.SSHException:`

Running screencloud from the terminal gave this information:
`[INFO] "Loaded 5 plugin(s)" 
[INFO] "Using bundled icon: :/systray/trayicon-gray.svg" 
[INFO] "Uploading screenshot to 'sftp'. Size: 139072 bytes" 
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
Traceback (most recent call last):
  File "<string>", line 100, in upload
  File "/home/evan/.local/share/data/screencloud/ScreenCloud/plugins/sftp/modules/paramiko/transport.py", line 1007, in connect
    self.start_client()
  File "/home/evan/.local/share/data/screencloud/ScreenCloud/plugins/sftp/modules/paramiko/transport.py", line 466, in start_client
    raise e
[WARN] "Failed to call upload() in SFTPUploader" 
paramiko.SSHException: Incompatible ssh peer (no acceptable kex algorithm)
[WARN] "Failed to call SFTPUploader.upload()
Traceback (most recent call last):
  File "<string>", line 100, in upload
  File "/home/evan/.local/share/data/screencloud/ScreenCloud/plugins/sftp/modules/paramiko/transport.py", line 1007, in connect
    self.start_client()
  File "/home/evan/.local/share/data/screencloud/ScreenCloud/plugins/sftp/modules/paramiko/transport.py", line 466, in start_client
    raise e
paramiko.SSHException: Incompatible ssh peer (no acceptable kex algorithm)" 
Got a buffer underflow! 
[WARN] "Error while playing audio. Code: 3"`

**Comment by olav-st** [comment]
The problem is probably this:
`paramiko.SSHException: Incompatible ssh peer`
might be because paramiko is outdated?

**Comment by evan3334** [comment]
If that's the problem, I'm not sure how to update it.

**Comment by olav-st** [comment]
Can you try now? I've updated the SFTP plugin.

**Comment by evan3334** [comment]
`[WARN] "Failed to write /root/i/pNh1Y0F9.png. Check permissions."`

This seems like it might be a problem on my end with the server, though I'm not sure

**Comment by olav-st** [comment]
You can try to check the sftp log. It should be in `/tmp/screencloud-sftp.log`
