### ISSUE TITLE
Error installing the dropbox plugin: ImportError: No module named typing

### ISSUE THREAD

**Issue by n1k0** [olav-st/screencloud#224]
Latest 1.3.0 on Ubuntu 16.04, enabling the dropbox plugin I'm getting this error:

```
Error in file: /home/niko/.local/share/screencloud/ScreenCloud/plugins/dropbox/main.py
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/niko/.local/share/screencloud/ScreenCloud/plugins/dropbox/modules/dropbox/__init__.py", line 3, in <module>
    from .dropbox import __version__, Dropbox, DropboxTeam, create_session
  File "/home/niko/.local/share/screencloud/ScreenCloud/plugins/dropbox/modules/dropbox/dropbox.py", line 19, in <module>
    from . import stone_serializers
  File "/home/niko/.local/share/screencloud/ScreenCloud/plugins/dropbox/modules/dropbox/stone_serializers.py", line 23, in <module>
    from . import stone_validators as bv
  File "/home/niko/.local/share/screencloud/ScreenCloud/plugins/dropbox/modules/dropbox/stone_validators.py", line 21, in <module>
    from typing import Optional
ImportError: No module named typing
```

The plugin is still added to the list of installed ones, but when I try to access its settings, I'm getting:

```
Failed to call DropboxUploader.showSettingsUI()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name DropboxUploader
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'DropboxUploader' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'dropbox_u' is not defined
```

**Comment by n1k0** [comment]
Also, I wanted to thank you for your work on this project; it's when it suddenly stops working that you realize how much you can't live with it anymore. Cheers :beers:

**Comment by torpet** [comment]
I am  having the same issue.

**Comment by joshsouza** [comment]
I am also having the same issue. Fresh install of 16.04, following install instructions for ScreenCloud. Installation worked, when I chose to enable Dropbox, I immediately received this error.

**Comment by HyperUa** [comment]
The same problem =(

**Comment by skizot722** [comment]
Same problem here.  Ubuntu 16.04 as well.

**Comment by mescalito** [comment]
+1 same in windows 7

**Comment by olav-st** [comment]
I've pushed a new version that should fix this, can anyone confirm? (restart ScreenCloud to get the update)

**Comment by n1k0** [comment]
@olav-st latest release nicely fixes the issue, thank you!
