### ISSUE TITLE
Error with plugins importing urllib

### ISSUE THREAD

**Issue by RezzedUp** [olav-st/screencloud#225]
I'm in the process of updating a plugin to python 3, but importing urllib is throwing errors:

```
Error in file: C:/Users/Admin/AppData/Roaming/screencloud/ScreenCloud/plugins/tokenupload/main.py
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\Program Files (x86)\ScreenCloud\python35.zip\urllib\request.py", line 88, in <module>
  File "C:\Program Files (x86)\ScreenCloud\python35.zip\http\client.py", line 71, in <module>
  File "C:\Program Files (x86)\ScreenCloud\python35.zip\email\parser.py", line 12, in <module>
  File "C:\Program Files (x86)\ScreenCloud\python35.zip\email\feedparser.py", line 27, in <module>
  File "C:\Program Files (x86)\ScreenCloud\python35.zip\email\message.py", line 16, in <module>
  File "C:\Program Files (x86)\ScreenCloud\python35.zip\email\utils.py", line 30, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

Line 3:

``` python
import urllib.request, urllib.error, urllib.parse
```

All other imports are working correctly: (so far)

``` python
import ScreenCloud
import json
import urllib.request, urllib.error, urllib.parse # not these

from PythonQt.QtCore import QSettings, QByteArray, QBuffer, QIODevice, QFile
from PythonQt.QtGui import QWidget, QDialog
from PythonQt.QtUiTools import QUiLoader
```

---

I'm on Windows 10 running screencloud 1.3.0

**Comment by olav-st** [comment]
There's something weird going on with the installer on some windows systems. If you take a look in `C:\Program Files\ScreenCloud` you'll probably see DLLs for both Qt4 and Qt5. For some reason the upgrade to 1.3.0 dosen't remove all the old DLLs.

Doing a clean install should solve it.

**Comment by RezzedUp** [comment]
A clean screencloud installation did fix the issue. Thanks!
