### ISSUE TITLE
Script error in plugin "ftp"

### ISSUE THREAD

**Issue by nayuma** [olav-st/screencloud#243]
I'm using the latest build from the repository. Please fix as soon as possible. (Running Xubuntu 16.04)
`Failed to call FTPUploader.isConfigured()
Traceback (most recent call last):
  File "<string>", line 74, in upload
  File "/usr/lib/python2.7/ftplib.py", line 135, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known`

**Comment by SuchYare** [comment]
I have viewed other open issues and it appears that the author does not have enough time to actively commit, I will reopen this issue in the near future (possibly 1-2 weeks)

**Comment by nayuma** [comment]
I'm gonna go ahead and reopen this
