### ISSUE TITLE
Error compiling on Fedora 24

### ISSUE THREAD

**Issue by mRokita** [olav-st/screencloud#246]
OS: Fedora Workspace 24 64bit
I've set DISABLE_QT_KEYWORDS to ON in order to make it pass some error, but now I'm stuck on this error:
```
[mrokita@R510JK build]$ cmake ..
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:24 (MESSAGE):
  ScreenCloud API keys not set, you won't be able to use the client with
  screencloud.net.  (You'll still be able to compile)


-- Found quazip: /usr/lib64/libquazip.so  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Found PythonLibs: /usr/lib64/libpython3.5m.so (found suitable version "3.5.1", minimum required is "3.3") 
-- Using PythonQt_QtAll for Qt bindings.
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2j") 
-- OpenSSL libraries: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so
-- Including QtSingleApplication and parts of LibQxt.
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mrokita/screencloud/build
[mrokita@R510JK build]$ make
Scanning dependencies of target screencloud_automoc
[  1%] Automatic moc for target screencloud
Generating moc_qxtglobalshortcut.cpp
Generating moc_qtlocalpeer.cpp
Generating moc_qtsingleapplication.cpp
Generating moc_audionotifier.cpp
Generating moc_changelogdialog.cpp
Generating moc_downloadupdatedialog.cpp
Generating moc_editordialog.cpp
Generating moc_licensesdialog.cpp
Generating moc_logindialog.cpp
Generating moc_plugindialog.cpp
Generating moc_preferencesdialog.cpp
Generating moc_savescreenshotdialog.cpp
Generating moc_colorpropertytooleditor.cpp
Generating moc_fontpropertytooleditor.cpp
Generating moc_abstractgraphicsrectitem.cpp
Generating moc_arrowgraphicsitem.cpp
Generating moc_boxgraphicsitem.cpp
Generating moc_boxtextgraphicsitem.cpp
Generating moc_ellipsegraphicsitem.cpp
Generating moc_handlegraphicsitem.cpp
Generating moc_kaptiongraphicsitem.cpp
Generating moc_numbereditem.cpp
Generating moc_textgraphicsitem.cpp
Generating moc_kaptiongraphicstoolkit.cpp
Generating moc_numberpropertytooleditor.cpp
Generating moc_numberselector.cpp
Generating moc_propertytooleditor.cpp
Generating moc_qcolorbutton.cpp
Generating moc_scalepropertytooleditor.cpp
Generating moc_snapshotcanvas.cpp
Generating moc_activatepage.cpp
Generating moc_finishedpage.cpp
Generating moc_firstrunwizard.cpp
Generating moc_loginpage.cpp
Generating moc_newaccountpage.cpp
Generating moc_onlineservicespage.cpp
Generating moc_shortcutspage.cpp
Generating moc_welcomepage.cpp
Generating moc_busyoverlay.cpp
Generating moc_clickablelabel.cpp
Generating moc_pythonconsole.cpp
Generating moc_screenshotthumbview.cpp
Generating moc_selectionoverlay.cpp
Generating moc_hotkeyeventfilter.cpp
Generating moc_uploaderslistmodel.cpp
Generating moc_pluginmanager.cpp
Generating moc_screenshooter.cpp
Generating moc_systemtrayicon.cpp
Generating moc_clipboarduploader.cpp
Generating moc_pythonuploader.cpp
Generating moc_screenclouduploader.cpp
Generating moc_uploader.cpp
Generating moc_uploadmanager.cpp
Generating moc_updater.cpp
[  1%] Built target screencloud_automoc
[  2%] Generating ui_editordialog.h
[  3%] Generating qrc_icons.cpp
[  5%] Generating qrc_sounds.cpp
[  6%] Generating qrc_resources_linux.cpp
[  7%] Generating ui_downloadupdatedialog.h
[  8%] Generating ui_preferencesdialog.h
[ 10%] Generating ui_licensesdialog.h
[ 11%] Generating ui_savescreenshotdialog.h
[ 12%] Generating ui_plugindialog.h
[ 13%] Generating ui_logindialog.h
[ 15%] Generating ui_changelogdialog.h
Scanning dependencies of target screencloud
[ 16%] Building CXX object CMakeFiles/screencloud.dir/src/dialog/downloadupdatedialog.cpp.o
[ 17%] Building CXX object CMakeFiles/screencloud.dir/src/dialog/preferencesdialog.cpp.o
In file included from /home/mrokita/screencloud/src/uploaders/pythonuploader.h:24:0,
                 from /home/mrokita/screencloud/src/plugin/pluginmanager.h:23,
                 from /home/mrokita/screencloud/src/utils/updater.h:29,
                 from /home/mrokita/screencloud/src/dialog/preferencesdialog.h:36,
                 from /home/mrokita/screencloud/src/dialog/preferencesdialog.cpp:15:
/usr/include/PythonQt/PythonQt.h:504:1: error: ‘signals’ does not name a type
 signals:
 ^~~~~~~
CMakeFiles/screencloud.dir/build.make:159: polecenia dla obiektu 'CMakeFiles/screencloud.dir/src/dialog/preferencesdialog.cpp.o' nie powiodły się
make[2]: *** [CMakeFiles/screencloud.dir/src/dialog/preferencesdialog.cpp.o] Błąd 1
CMakeFiles/Makefile2:67: polecenia dla obiektu 'CMakeFiles/screencloud.dir/all' nie powiodły się
make[1]: *** [CMakeFiles/screencloud.dir/all] Błąd 2
Makefile:127: polecenia dla obiektu 'all' nie powiodły się
make: *** [all] Błąd 
```

**Comment by olav-st** [comment]
You need to compile your own version of PythonQt. The one that ships with Fedora is oooold.

**Comment by mRokita** [comment]
Ok, I've compiled it, i have another problem now though :(
```CMakeFiles/screencloud.dir/src/uploaders/pythonuploader.cpp.o: In function `PythonUploader::upload(QImage const&, QString)':
pythonuploader.cpp:(.text+0x13c9): undefined reference to `PythonQtObjectPtr::call(QString const&, QList<QVariant> const&, QMap<QString, QVariant> const&)'
CMakeFiles/screencloud.dir/src/uploaders/pythonuploader.cpp.o: In function `PythonUploader::isConfigured()':
pythonuploader.cpp:(.text+0x20e1): undefined reference to `PythonQtObjectPtr::call(QString const&, QList<QVariant> const&, QMap<QString, QVariant> const&)'
CMakeFiles/screencloud.dir/src/uploaders/pythonuploader.cpp.o: In function `PythonUploader::getFilename()':
pythonuploader.cpp:(.text+0x262a): undefined reference to `PythonQtObjectPtr::call(QString const&, QList<QVariant> const&, QMap<QString, QVariant> const&)'
CMakeFiles/screencloud.dir/src/main.cpp.o: In function `main':
main.cpp:(.text+0x75f): undefined reference to `PythonQt::hadError() const'
collect2: error: ld returned 1 exit status
CMakeFiles/screencloud.dir/build.make:1900: polecenia dla obiektu 'screencloud-1.3.1' nie powiodły się
make[2]: *** [screencloud-1.3.1] Błąd 1
CMakeFiles/Makefile2:67: polecenia dla obiektu 'CMakeFiles/screencloud.dir/all' nie powiodły się
make[1]: *** [CMakeFiles/screencloud.dir/all] Błąd 2
Makefile:127: polecenia dla obiektu 'all' nie powiodły się
make: *** [all] Błąd 2```

**Comment by mRokita** [comment]
ouch, i've compiled it finally. 
but now:
```
[mrokita@R510JK build]$ ./screencloud

(screencloud:13090): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3209:17: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(screencloud:13090): Gtk-WARNING **: Theme parsing error: gtk-dark.css:6352:23: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'

(screencloud:13090): Gtk-WARNING **: Theme parsing error: gtk-dark.css:6362:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(screencloud:13090): Gtk-WARNING **: Theme parsing error: gtk-dark.css:6412:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(screencloud:13090): Gtk-WARNING **: Theme parsing error: gtk-dark.css:6525:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(screencloud:13090): Gtk-WARNING **: Theme parsing error: gtk-dark.css:6548:52: The :prelight pseudo-class is deprecated. Use :hover instead.
Segmentation fault (zrzut pamięci)
```

**Comment by olav-st** [comment]
Probably a Qt 4/5 version mismatch. Check that all libraries (PythonQt, QuaZip, etc) are compiled against Qt 5.

**Comment by mRokita** [comment]
Thank you :) It works, finally!
But I've done something wrong when installing PythonQt - I can't import it. I will try to fix it by myself though.
Still, it can't find the SFTPUploader module, how can I fix it?

**Comment by mRokita** [comment]
sys.path:
['/home/mrokita/.local/share/screencloud/ScreenCloud/plugins/ftp/modules', '/home/mrokita/.local/share/screencloud/ScreenCloud/plugins/sftp/modules', '/home/mrokita/.local/share/screencloud/ScreenCloud/plugins/sftp/modules', '/usr/share/screencloud/modules', '/usr/local/share/screencloud/modules', '/home/mrokita/.local/share/screencloud/modules', '/usr/local/bin/modules', '/usr/lib64/python35.zip', '/usr/lib64/python3.5/', '/usr/lib64/python3.5/plat-linux', '/usr/lib64/python3.5/lib-dynload']

**Comment by mRokita** [comment]
Errors:

```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ImportError: No module named 'PythonQt.QtUiTools'; 'PythonQt' is not a package
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'SFTPUploader'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'SFTPUploader' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'sftp_u' is not defined```
