### ISSUE TITLE
Segfault on Ubuntu 18.04

### ISSUE THREAD

**Issue by CleverWhiteWolf** [olav-st/screencloud#345]
Hello,

I have been using ScreenCloud v1.3.0 for a long time and all worked well until today when I have updated packages of Ubuntu 18.04.

The software just starts and crashes with segfault error.

```
Jun 13 10:20:36 workstation kernel: [ 3808.446089] QNetworkAccessM[11500]: segfault at 0 ip 00007febc567c0d4 sp 00007feb80866718 error 4 in libQt5Network.so.5.9.5[7febc55e8000+183000]
```

I tried to use GDB utility and got the following:
```
% gdb /usr/bin/screencloud
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/screencloud...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/screencloud 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe200b700 (LWP 18980)]
[New Thread 0x7fffddcf1700 (LWP 18981)]
[New Thread 0x7fffd48b0700 (LWP 18982)]
[New Thread 0x7fffcffff700 (LWP 18983)]
[New Thread 0x7fffcf7fe700 (LWP 18984)]
[New Thread 0x7fffceffd700 (LWP 18985)]
[INFO] "Loaded 2 plugin(s)"
[New Thread 0x7fffb4c53700 (LWP 18986)]
[INFO] "Using bundled icon: :/systray/trayicon-gray.svg"
[New Thread 0x7fff9ffff700 (LWP 18987)]
[New Thread 0x7fff9f7fe700 (LWP 18988)]
[New Thread 0x7fff97984700 (LWP 18989)]
[New Thread 0x7fff96d6d700 (LWP 18990)]

Thread 9 "QNetworkAccessM" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9ffff700 (LWP 18987)]
0x00007ffff4f0b0d4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
(gdb) backtrace full
#0  0x00007ffff4f0b0d4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
No symbol table info available.
#1  0x00007ffff4f09ca2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
No symbol table info available.
#2  0x00007ffff427d122 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#3  0x00007ffff535782c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#4  0x00007ffff535f0f4 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#5  0x00007ffff424d9a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#6  0x00007ffff425011d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#7  0x00007ffff42a72c3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#8  0x00007fffecd56317 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#9  0x00007fffecd56550 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#10 0x00007fffecd565dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#11 0x00007ffff42a68ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#12 0x00007ffff424b9ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#13 0x00007ffff406a22a in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#14 0x00007ffff406f16d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#15 0x00007fffee1ec6db in start_thread (arg=0x7fff9ffff700) at pthread_create.c:463
        pd = 0x7fff9ffff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140735877740288, -52222238390542786, 140735877737920, 0, 16292560, 140737488341184, 52151869188546110, 
                52253306866572862}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#16 0x00007ffff33b488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```

I tried to downgrade libqt5network and libqt5core system packages but this did not help.
Probably the reason of the issue is not in those packages and is more related with "QNetworkAccessM" error message. 
However, I am not good at debugging so may be I am wrong.

Could you help me in understanding the real reason of the issue?

Thanks in advance.

**Comment by olav-st** [comment]
Don't know what the problem is, but I think the easiest solutions is to use version 1.4.0 (using either the snap or the AppImage) or to compile your own version if you need to use 1.3.0.
