### ISSUE TITLE
Imgur having issues

### ISSUE THREAD

**Issue by Nothing4You** [olav-st/screencloud#50]
Hi,
I'm on latest git (fa02d5c) with latest plugins (removed and added again).

I just tried to upload something to imgur.
Result:

```
[INFO] "Uploading screenshot to 'imgur'. Size: 336168 bytes" 
[New Thread 0x7fffc3382700 (LWP 9432)]
Traceback (most recent call last):
  File "<string>", line 85, in upload
  File "/home/rschwab/.local/share/data/screencloud/ScreenCloud/plugins/imgur/modules/pyimgur/__init__.py", line 1065, in refresh_access_token
    data_field=None)
  File "/home/rschwab/.local/share/data/screencloud/ScreenCloud/plugins/imgur/modules/pyimgur/__init__.py", line 704, in _send_request
    result = request.send_request(url, **kwargs)
  File "/home/rschwab/.local/share/data/screencloud/ScreenCloud/plugins/imgur/modules/pyimgur/request.py", line 95, in send_request
    error_msg = "Imgur ERROR message: %s" % content['error']
[WARN] "Failed to call upload() in ImgurUploader" 
KeyError: 'error'
[WARN] "Failed to call ImgurUploader.upload()
Traceback (most recent call last):
  File "<string>", line 85, in upload
  File "/home/rschwab/.local/share/data/screencloud/ScreenCloud/plugins/imgur/modules/pyimgur/__init__.py", line 1065, in refresh_access_token
    data_field=None)
  File "/home/rschwab/.local/share/data/screencloud/ScreenCloud/plugins/imgur/modules/pyimgur/__init__.py", line 704, in _send_request
    result = request.send_request(url, **kwargs)
  File "/home/rschwab/.local/share/data/screencloud/ScreenCloud/plugins/imgur/modules/pyimgur/request.py", line 95, in send_request
    error_msg = "Imgur ERROR message: %s" % content['error']
KeyError: 'error'" 
```

Then I double clicked on the imgur plugin to edit its settings, result was

```
[WARN] "Failed to call showSettingsUI() in ImgurUploader"
```

in addition to the normal settings dialog.
I closed the plugin dialog with ok, and closed the screencloud settings dialog.
Then I tried another upload:

```
[INFO] "Uploading screenshot to 'imgur'. Size: 18584 bytes" 
[New Thread 0x7fffda36a700 (LWP 9466)]
Traceback (most recent call last):
  File "<string>", line 85, in upload
[WARN] "Failed to call upload() in ImgurUploader" 
  File "/home/rschwab/.local/share/data/screencloud/ScreenCloud/plugins/imgur/modules/pyimgur/__init__.py", line 1065, in refresh_access_token
    data_field=None)
  File "/home/rschwab/.local/share/data/screencloud/ScreenCloud/plugins/imgur/modules/pyimgur/__init__.py", line 704, in _send_request
    result = request.send_request(url, **kwargs)
  File "/home/rschwab/.local/share/data/screencloud/ScreenCloud/plugins/imgur/modules/pyimgur/request.py", line 95, in send_request
    error_msg = "Imgur ERROR message: %s" % content['error']
KeyError: 'error'
[WARN] "Failed to call ImgurUploader.upload()
Traceback (most recent call last):
  File "<string>", line 85, in upload
" 
```

Then I opened the plugin settings again

```
[WARN] "Failed to call showSettingsUI() in ImgurUploader"
```

After switching to anonymous upload it works.
Switching back to my account fails again.
I then logged out and in again and suddenly it works again.

**Comment by Nothing4You** [comment]
This is still an issue.

Yesterday or so I logged in to imgur and today it doesn't work anymore.
Different traceback now though.

I'm currently on windows using the latest available version (1.1.6).
I tried a few times, I think I had a different trace earlier.

![Screenshot of traceback](https://i.imgur.com/FxzgCIz.png)

Another issue, not sure whether related or not, after I removed the account (got several errors after upload errors, might also have been before that), is that I'm getting this when I open the imgur preferences, not sure exactly how to reproduce that, after closing and reopening it's not always there.

![Screenshot of settings error](https://i.imgur.com/IXs7vqe.png)
